{% set name = "metafun-test" %}
{% set version = "0.1" %}
{% set sha256 = "5585165fd86b6e14648ac3419a32778b65ca7a350a1dacadd7448ae59b488181" %}

package:
  name: {{ metaFun|metafun }}
  version: {{ 0.1.0 }}

source:
  url: https://github.com/aababc1/metaFun/archive/refs/tags/v0.1.0.tar.gz
  sha256: {{ 5585165fd86b6e14648ac3419a32778b65ca7a350a1dacadd7448ae59b488181 }}

build:
  number: 0
  preserve_empty_dirs: true
  noarch: generic

requirements:
  host:
    - python >=3.12
    - pip
  run:
    - python >=3.12
    - apptainer >=1.3.0
    - nextflow >=24.04.2
    - dash >=2.17.1
    - dash-bootstrap-components >=1.7.1
    - dash-core-components >=2.0.0
    - dash-html-components >=2.0.0
    - dash-table >=5.0.0
    - dash-daq >=0.5.0
    - plotly >=5.22.0
    - pandas >=2.2.2
    - tqdm >=4.66.4
    - sylph >=0.6.1
    - numpy >=2.0.0

test:
  commands:
    - which metafun_test
    - metafun_test -h

about:
  home: https://github.com/aababc1/metaFun
  license: MIT
  license_file: LICENSE  # 소스 코드에 LICENSE 파일이 있는지 확인하세요
  summary: Custom package for metafun workflow management
  description: |
    A comprehensive package that includes custom scripts and workflows
    for metafun analysis pipeline.
  
  extra:
    recipe-maintainers:
     - aababc1
